// Code generated by hertz generator.

package gateway

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getboardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getjudgeresultMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitMw() []app.HandlerFunc {
	// your code...
	return nil
}
