// Code generated by Kitex v0.9.1. DO NOT EDIT.

package submit

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	submit "github.com/imag-er/wendingcup/rpc_gen/kitex_gen/submit"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Submit": kitex.NewMethodInfo(
		submitHandler,
		newSubmitArgs,
		newSubmitResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	submitServiceInfo                = NewServiceInfo()
	submitServiceInfoForClient       = NewServiceInfoForClient()
	submitServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return submitServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return submitServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return submitServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Submit"
	handlerType := (*submit.Submit)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "submit",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func submitHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(submit.SubmitRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(submit.Submit).Submit(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SubmitArgs:
		success, err := handler.(submit.Submit).Submit(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SubmitResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSubmitArgs() interface{} {
	return &SubmitArgs{}
}

func newSubmitResult() interface{} {
	return &SubmitResult{}
}

type SubmitArgs struct {
	Req *submit.SubmitRequest
}

func (p *SubmitArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(submit.SubmitRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SubmitArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SubmitArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SubmitArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SubmitArgs) Unmarshal(in []byte) error {
	msg := new(submit.SubmitRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SubmitArgs_Req_DEFAULT *submit.SubmitRequest

func (p *SubmitArgs) GetReq() *submit.SubmitRequest {
	if !p.IsSetReq() {
		return SubmitArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SubmitArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SubmitArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SubmitResult struct {
	Success *submit.SubmitResponse
}

var SubmitResult_Success_DEFAULT *submit.SubmitResponse

func (p *SubmitResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(submit.SubmitResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SubmitResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SubmitResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SubmitResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SubmitResult) Unmarshal(in []byte) error {
	msg := new(submit.SubmitResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SubmitResult) GetSuccess() *submit.SubmitResponse {
	if !p.IsSetSuccess() {
		return SubmitResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SubmitResult) SetSuccess(x interface{}) {
	p.Success = x.(*submit.SubmitResponse)
}

func (p *SubmitResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SubmitResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Submit(ctx context.Context, Req *submit.SubmitRequest) (r *submit.SubmitResponse, err error) {
	var _args SubmitArgs
	_args.Req = Req
	var _result SubmitResult
	if err = p.c.Call(ctx, "Submit", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
