// Code generated by Kitex v0.9.1. DO NOT EDIT.

package submit

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	submit "github.com/imag-er/wendingcup/rpc_gen/kitex_gen/submit"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SubmitFile": kitex.NewMethodInfo(
		submitFileHandler,
		newSubmitFileArgs,
		newSubmitFileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	submitServiceInfo                = NewServiceInfo()
	submitServiceInfoForClient       = NewServiceInfoForClient()
	submitServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return submitServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return submitServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return submitServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Submit"
	handlerType := (*submit.Submit)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "submit",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func submitFileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(submit.SubmitFileRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(submit.Submit).SubmitFile(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SubmitFileArgs:
		success, err := handler.(submit.Submit).SubmitFile(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SubmitFileResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSubmitFileArgs() interface{} {
	return &SubmitFileArgs{}
}

func newSubmitFileResult() interface{} {
	return &SubmitFileResult{}
}

type SubmitFileArgs struct {
	Req *submit.SubmitFileRequest
}

func (p *SubmitFileArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(submit.SubmitFileRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SubmitFileArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SubmitFileArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SubmitFileArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SubmitFileArgs) Unmarshal(in []byte) error {
	msg := new(submit.SubmitFileRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SubmitFileArgs_Req_DEFAULT *submit.SubmitFileRequest

func (p *SubmitFileArgs) GetReq() *submit.SubmitFileRequest {
	if !p.IsSetReq() {
		return SubmitFileArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SubmitFileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SubmitFileArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SubmitFileResult struct {
	Success *submit.SubmitFileResponse
}

var SubmitFileResult_Success_DEFAULT *submit.SubmitFileResponse

func (p *SubmitFileResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(submit.SubmitFileResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SubmitFileResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SubmitFileResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SubmitFileResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SubmitFileResult) Unmarshal(in []byte) error {
	msg := new(submit.SubmitFileResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SubmitFileResult) GetSuccess() *submit.SubmitFileResponse {
	if !p.IsSetSuccess() {
		return SubmitFileResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SubmitFileResult) SetSuccess(x interface{}) {
	p.Success = x.(*submit.SubmitFileResponse)
}

func (p *SubmitFileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SubmitFileResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SubmitFile(ctx context.Context, Req *submit.SubmitFileRequest) (r *submit.SubmitFileResponse, err error) {
	var _args SubmitFileArgs
	_args.Req = Req
	var _result SubmitFileResult
	if err = p.c.Call(ctx, "SubmitFile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
