// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package submit

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *SubmitRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SubmitRequest[number], err)
}

func (x *SubmitRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.TeamId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SubmitRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.File, offset, err = fastpb.ReadBytes(buf, _type)
	return offset, err
}

func (x *SubmitResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SubmitResponse[number], err)
}

func (x *SubmitResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Code, offset, err = fastpb.ReadUint32(buf, _type)
	return offset, err
}

func (x *SubmitResponse) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Msg, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SubmitResponse) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.SubmitId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SubmitRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *SubmitRequest) fastWriteField1(buf []byte) (offset int) {
	if x.TeamId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetTeamId())
	return offset
}

func (x *SubmitRequest) fastWriteField2(buf []byte) (offset int) {
	if len(x.File) == 0 {
		return offset
	}
	offset += fastpb.WriteBytes(buf[offset:], 2, x.GetFile())
	return offset
}

func (x *SubmitResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *SubmitResponse) fastWriteField1(buf []byte) (offset int) {
	if x.Code == 0 {
		return offset
	}
	offset += fastpb.WriteUint32(buf[offset:], 1, x.GetCode())
	return offset
}

func (x *SubmitResponse) fastWriteField2(buf []byte) (offset int) {
	if x.Msg == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetMsg())
	return offset
}

func (x *SubmitResponse) fastWriteField3(buf []byte) (offset int) {
	if x.SubmitId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetSubmitId())
	return offset
}

func (x *SubmitRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *SubmitRequest) sizeField1() (n int) {
	if x.TeamId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetTeamId())
	return n
}

func (x *SubmitRequest) sizeField2() (n int) {
	if len(x.File) == 0 {
		return n
	}
	n += fastpb.SizeBytes(2, x.GetFile())
	return n
}

func (x *SubmitResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *SubmitResponse) sizeField1() (n int) {
	if x.Code == 0 {
		return n
	}
	n += fastpb.SizeUint32(1, x.GetCode())
	return n
}

func (x *SubmitResponse) sizeField2() (n int) {
	if x.Msg == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetMsg())
	return n
}

func (x *SubmitResponse) sizeField3() (n int) {
	if x.SubmitId == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetSubmitId())
	return n
}

var fieldIDToName_SubmitRequest = map[int32]string{
	1: "TeamId",
	2: "File",
}

var fieldIDToName_SubmitResponse = map[int32]string{
	1: "Code",
	2: "Msg",
	3: "SubmitId",
}
