// Code generated by Kitex v0.9.1. DO NOT EDIT.

package judge

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	judge "github.com/imag-er/wendingcup/rpc_gen/kitex_gen/judge"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Judge": kitex.NewMethodInfo(
		judgeHandler,
		newJudgeArgs,
		newJudgeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	judgeServiceInfo                = NewServiceInfo()
	judgeServiceInfoForClient       = NewServiceInfoForClient()
	judgeServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return judgeServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return judgeServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return judgeServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Judge"
	handlerType := (*judge.Judge)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "judge",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func judgeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(judge.JudgeRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(judge.Judge).Judge(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *JudgeArgs:
		success, err := handler.(judge.Judge).Judge(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*JudgeResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newJudgeArgs() interface{} {
	return &JudgeArgs{}
}

func newJudgeResult() interface{} {
	return &JudgeResult{}
}

type JudgeArgs struct {
	Req *judge.JudgeRequest
}

func (p *JudgeArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(judge.JudgeRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *JudgeArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *JudgeArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *JudgeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *JudgeArgs) Unmarshal(in []byte) error {
	msg := new(judge.JudgeRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var JudgeArgs_Req_DEFAULT *judge.JudgeRequest

func (p *JudgeArgs) GetReq() *judge.JudgeRequest {
	if !p.IsSetReq() {
		return JudgeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *JudgeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *JudgeArgs) GetFirstArgument() interface{} {
	return p.Req
}

type JudgeResult struct {
	Success *judge.JudgeResponse
}

var JudgeResult_Success_DEFAULT *judge.JudgeResponse

func (p *JudgeResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(judge.JudgeResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *JudgeResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *JudgeResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *JudgeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *JudgeResult) Unmarshal(in []byte) error {
	msg := new(judge.JudgeResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *JudgeResult) GetSuccess() *judge.JudgeResponse {
	if !p.IsSetSuccess() {
		return JudgeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *JudgeResult) SetSuccess(x interface{}) {
	p.Success = x.(*judge.JudgeResponse)
}

func (p *JudgeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *JudgeResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Judge(ctx context.Context, Req *judge.JudgeRequest) (r *judge.JudgeResponse, err error) {
	var _args JudgeArgs
	_args.Req = Req
	var _result JudgeResult
	if err = p.c.Call(ctx, "Judge", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
