// Code generated by Kitex v0.9.1. DO NOT EDIT.

package board

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	board "github.com/imag-er/wendingcup/rpc_gen/kitex_gen/board"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Board": kitex.NewMethodInfo(
		boardHandler,
		newBoardArgs,
		newBoardResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	boardServiceInfo                = NewServiceInfo()
	boardServiceInfoForClient       = NewServiceInfoForClient()
	boardServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return boardServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return boardServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return boardServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Board"
	handlerType := (*board.Board)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "board",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func boardHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(board.BoardRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(board.Board).Board(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BoardArgs:
		success, err := handler.(board.Board).Board(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BoardResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBoardArgs() interface{} {
	return &BoardArgs{}
}

func newBoardResult() interface{} {
	return &BoardResult{}
}

type BoardArgs struct {
	Req *board.BoardRequest
}

func (p *BoardArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(board.BoardRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *BoardArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *BoardArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *BoardArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BoardArgs) Unmarshal(in []byte) error {
	msg := new(board.BoardRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BoardArgs_Req_DEFAULT *board.BoardRequest

func (p *BoardArgs) GetReq() *board.BoardRequest {
	if !p.IsSetReq() {
		return BoardArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BoardArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BoardArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BoardResult struct {
	Success *board.BoardResponse
}

var BoardResult_Success_DEFAULT *board.BoardResponse

func (p *BoardResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(board.BoardResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *BoardResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *BoardResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *BoardResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BoardResult) Unmarshal(in []byte) error {
	msg := new(board.BoardResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BoardResult) GetSuccess() *board.BoardResponse {
	if !p.IsSetSuccess() {
		return BoardResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BoardResult) SetSuccess(x interface{}) {
	p.Success = x.(*board.BoardResponse)
}

func (p *BoardResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BoardResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Board(ctx context.Context, Req *board.BoardRequest) (r *board.BoardResponse, err error) {
	var _args BoardArgs
	_args.Req = Req
	var _result BoardResult
	if err = p.c.Call(ctx, "Board", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
