// Code generated by Kitex v0.9.1. DO NOT EDIT.

package board

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	board "github.com/imag-er/wendingcup/rpc_gen/kitex_gen/board"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetBoard(ctx context.Context, Req *board.GetBoardRequest, callOptions ...callopt.Option) (r *board.GetBoardResponse, err error)
	AppendJudgeResult(ctx context.Context, Req *board.AppendJudgeResultRequest, callOptions ...callopt.Option) (r *board.AppendJudgeResultResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kBoardClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kBoardClient struct {
	*kClient
}

func (p *kBoardClient) GetBoard(ctx context.Context, Req *board.GetBoardRequest, callOptions ...callopt.Option) (r *board.GetBoardResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetBoard(ctx, Req)
}

func (p *kBoardClient) AppendJudgeResult(ctx context.Context, Req *board.AppendJudgeResultRequest, callOptions ...callopt.Option) (r *board.AppendJudgeResultResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AppendJudgeResult(ctx, Req)
}
